# Generated by Django 5.2.11 on 2026-03-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UtilsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('utilsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cameras.utilsdata')),
                ('name', models.CharField(max_length=200, verbose_name='Modelo')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Parte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='cameras/datasheets/', verbose_name='Ficha Técnica')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cameras/images/', verbose_name='Imagen')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cameras.brands', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de Cámara',
                'verbose_name_plural': 'Modelos de Cámara',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'name')},
            },
            bases=('cameras.utilsdata',),
        ),
        migrations.CreateModel(
            name='CameraConfiguration',
            fields=[
                ('utilsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cameras.utilsdata')),
                ('max_resolution', models.CharField(choices=[('720p', '720p (1MP)'), ('1080p', '1080p (2MP)'), ('3mp', '3MP'), ('4mp', '4MP'), ('5mp', '5MP'), ('6mp', '6MP'), ('8mp', '8MP / 4K'), ('12mp', '12MP'), ('custom', 'Personalizado')], max_length=20, verbose_name='Resolución Máxima')),
                ('custom_resolution', models.CharField(blank=True, max_length=50, verbose_name='Resolución Personalizada')),
                ('compression', models.CharField(choices=[('h264', 'H.264'), ('h265', 'H.265'), ('h265+', 'H.265+'), ('h264+', 'H.264+'), ('mjpeg', 'MJPEG')], default='h265', max_length=20, verbose_name='Compresión')),
                ('max_fps', models.PositiveIntegerField(default=30, verbose_name='FPS Máximo')),
                ('bitrate_kbps', models.PositiveIntegerField(default=2048, verbose_name='Bitrate (Kbps)')),
                ('streams_count', models.PositiveIntegerField(default=2, verbose_name='Número de Streams')),
                ('default_ip', models.GenericIPAddressField(default='192.168.1.64', verbose_name='IP por Defecto')),
                ('http_port', models.PositiveIntegerField(default=80, verbose_name='Puerto HTTP')),
                ('rtsp_port', models.PositiveIntegerField(default=554, verbose_name='Puerto RTSP')),
                ('https_port', models.PositiveIntegerField(default=443, verbose_name='Puerto HTTPS')),
                ('protocol', models.CharField(choices=[('rtsp', 'RTSP'), ('onvif', 'ONVIF'), ('rtmp', 'RTMP'), ('http', 'HTTP'), ('https', 'HTTPS')], default='rtsp', max_length=10, verbose_name='Protocolo Principal')),
                ('onvif_supported', models.BooleanField(default=True, verbose_name='Soporte ONVIF')),
                ('poe_supported', models.BooleanField(default=True, verbose_name='Soporte PoE')),
                ('wifi_supported', models.BooleanField(default=False, verbose_name='Soporte WiFi')),
                ('focal_length_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Focal Mín (mm)')),
                ('focal_length_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Focal Máx (mm)')),
                ('horizontal_fov', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='FOV Horizontal (°)')),
                ('optical_zoom', models.PositiveIntegerField(default=1, verbose_name='Zoom Óptico (x)')),
                ('digital_zoom', models.PositiveIntegerField(default=1, verbose_name='Zoom Digital (x)')),
                ('ir_distance_meters', models.PositiveIntegerField(default=30, verbose_name='Distancia IR (m)')),
                ('night_mode', models.CharField(choices=[('ir', 'Infrarrojo (IR)'), ('color', 'Full Color Night'), ('starlight', 'Starlight'), ('thermal', 'Térmica'), ('none', 'Sin modo nocturno')], default='ir', max_length=20, verbose_name='Modo Nocturno')),
                ('motion_detection', models.BooleanField(default=True, verbose_name='Detección de Movimiento')),
                ('face_detection', models.BooleanField(default=False, verbose_name='Detección Facial')),
                ('license_plate_recognition', models.BooleanField(default=False, verbose_name='Reconocimiento de Placas (LPR)')),
                ('audio_in', models.BooleanField(default=False, verbose_name='Entrada de Audio')),
                ('audio_out', models.BooleanField(default=False, verbose_name='Salida de Audio')),
                ('power_consumption_watts', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Consumo (W)')),
                ('poe_class', models.CharField(blank=True, max_length=20, verbose_name='Clase PoE')),
                ('ip_rating', models.CharField(default='IP67', max_length=10, verbose_name='Clasificación IP')),
                ('ik_rating', models.CharField(blank=True, max_length=10, verbose_name='Clasificación IK')),
                ('temp_min', models.IntegerField(default=-30, verbose_name='Temp. Mínima (°C)')),
                ('temp_max', models.IntegerField(default=60, verbose_name='Temp. Máxima (°C)')),
                ('rtsp_main_stream', models.CharField(default='rtsp://{user}:{password}@{ip}:{port}/Streaming/Channels/101', max_length=300, verbose_name='RTSP Stream Principal')),
                ('rtsp_sub_stream', models.CharField(blank=True, default='rtsp://{user}:{password}@{ip}:{port}/Streaming/Channels/102', max_length=300, verbose_name='RTSP Sub-Stream')),
                ('default_username', models.CharField(default='admin', max_length=100, verbose_name='Usuario por Defecto')),
                ('default_password', models.CharField(default='admin12345', max_length=100, verbose_name='Contraseña por Defecto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('configuration_guide', models.TextField(blank=True, verbose_name='Guía de Configuración')),
                ('camera_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='cameras.cameramodel', verbose_name='Modelo de Cámara')),
            ],
            options={
                'verbose_name': 'Configuración de Cámara',
                'verbose_name_plural': 'Configuraciones de Cámara',
            },
            bases=('cameras.utilsdata',),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('utilsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cameras.utilsdata')),
                ('type_camera', models.CharField(choices=[('bullet', 'Bullet'), ('dome', 'Domo'), ('ptz', 'PTZ'), ('fisheye', 'Ojo de Pez'), ('box', 'Box'), ('covert', 'Covert'), ('thermal', 'Térmica'), ('multisensor', 'Multisensor')], max_length=20, verbose_name='Tipo camara')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Identificador')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('username', models.CharField(default='admin', max_length=100, verbose_name='Usuario')),
                ('password', models.CharField(default='admin12345', max_length=100, verbose_name='Contraseña')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Ubicación')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='Zona')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('camera_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cameras.cameramodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
                'ordering': ['name'],
            },
            bases=('cameras.utilsdata',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('utilsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cameras.utilsdata')),
                ('sd_card_slot', models.BooleanField(default=True, verbose_name='Ranura SD')),
                ('max_sd_capacity_gb', models.PositiveIntegerField(blank=True, default=256, null=True, verbose_name='Capacidad SD Máx (GB)')),
                ('camera_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camara_que_guarda', to='cameras.cameramodel', verbose_name='Camara que guarda')),
            ],
            options={
                'verbose_name': 'Almacenamiento Camara',
                'verbose_name_plural': 'Almacenamiento camaras',
            },
            bases=('cameras.utilsdata',),
        ),
    ]
