# Generated by Django 5.2.12 on 2026-05-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_users_name_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono'),
        ),
    ]
