# Generated by Django 5.2.12 on 2026-05-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
